// Persisted Values
#define DEFAULT_WEATHER_SCALE "F"  // F Fahrenheit or C Celsius
#define DEFAULT_DEBUG_MODE false
#define DEFAULT_WEATHER_SERVICE "yahoo"
#define DEFAULT_DISPLAY_BATTERY true
#define DEFAULT_USE_FEELSLIKE true
#define DEFAULT_USE_AUTOFORECAST false
#define DEFAULT_H1_OFFSET 1
#define DEFAULT_H2_OFFSET 5
  
#define KEY_DEBUG_MODE 0
#define KEY_WEATHER_SERVICE 1
#define KEY_WEATHER_SCALE 2
#define KEY_DISPLAY_BATTERY 3
#define KEY_USE_FEELSLIKE 4
#define KEY_USE_H1_OFFSET 5
#define KEY_USE_H2_OFFSET 6
  
